### ISSUE TITLE
Attempting to use SpeedMod causes crash.

### ISSUE THREAD

**Issue by Xeddius** [1337Zero/Zombe#6]
Upon any attempt to use speedmod with any/all/none of the other mods enabled causes an instant crash.

**Comment by 1337Zero** [comment]
Heyho,

do u use any other mods (maybe that causes the crashes) ?
SP or MP ?
i know that on MP it can crash if u try to ignore dmg (from falling)

is only Speed activatet ?


and what really would help is the error log from your launcher :)

**Comment by Xeddius** [comment]
Details: OS: Windows 10, MC: 1.12.2, Optifine and Zombe are the only enabled/installed mods.
Error is as follows:
``Unreported exception thrown!
java.lang.NullPointerException
	at me.zero.cc.Zero_lite.Mods.SpeedMod.use(SpeedMod.java:94)
	at me.zero.cc.Zero_lite.LiteModMain.onTick(LiteModMain.java:251)
	at com.mumfrey.liteloader.core.event.HandlerList$Tickable9.onTick(HandlerList$Tickable9.java:100)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onTick(LiteLoaderEventBrokerClient.java:433)
	at bib.handler$onTick$zzn001(SourceFile:3203)
	at bib.az(SourceFile:1023)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ``

**Comment by 1337Zero** [comment]
Ok thats a problem which occures while using it in MP.
It should enable Godmode while "falling" or other stuff which simply wont work in mp.
Thats easy to fix.
Thx for that log

**Comment by 1337Zero** [comment]
Shouldnt crash with this:

https://github.com/1337Zero/Zombe/releases/tag/0.0.5.9.3

**Comment by Xeddius** [comment]
That was indeed the fix. Thank you for the quick response/edit!
